services:
  app:
    build: .
    volumes:
      - .:/app
      - mlruns:/app/mlruns
    env_file:
      - .env
    ports:
      - 5000:5000
    command: mlflow ui --workers 1 --host 0.0.0.0 --port 5000

volumes:
  mlruns:

